import { StyleSheet } from 'react-native';

// Login flow styles — extracted verbatim from the original screens/LoginScreen.js
// so behaviour is bit-for-bit identical.

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8FF',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: '100%',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 24,
  },
  header: {
    alignItems: 'center',
    marginBottom: 60,
    marginTop: 20,
  },
  formContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: '#B8D4F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  icon: {
    fontSize: 40,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#1E3A5F',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#4A6B8A',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  form: {
    gap: 20,
    paddingTop: 0,
    alignItems: 'stretch',
  },
  inputGroup: {
    gap: 12,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1E3A5F',
  },
  input: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 18,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#B8D4F1',
    color: '#1E3A5F',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    transition: 'all 0.2s ease',
  },
  connectButton: {
    height: 54,
    backgroundColor: '#4A90E2',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 32,
    shadowColor: '#1E3A5F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  connectButtonDisabled: {
    opacity: 0.5,
  },
  connectButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '600',
  },
  backButtonTop: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    alignSelf: 'flex-start',
  },
  backButtonText: {
    color: '#4A90E2',
    fontSize: 16,
    fontWeight: '500',
  },
  savedAccountsSection: {
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1E3A5F',
    marginBottom: 16,
  },
  headerToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F8FF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#B8D4F1',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  headerToggleText: {
    color: '#4A90E2',
    fontSize: 13,
    fontWeight: '600',
    marginRight: 6,
  },
  headerToggleIcon: {
    color: '#4A90E2',
    fontSize: 10,
    fontWeight: 'bold',
  },
  accountsContainer: {
    marginBottom: 16,
  },
  savedAccountItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8F4FD',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    overflow: 'hidden',
  },
  primaryAccountItem: {
    borderColor: '#4A90E2',
    borderWidth: 2,
    shadowOpacity: 0.18,
    transform: [{ scale: 1.02 }],
  },
  accountContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  accountAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#4A90E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  accountAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  accountInfo: {
    flex: 1,
  },
  accountHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  accountUsername: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1E3A5F',
    flex: 1,
  },
  recentBadge: {
    backgroundColor: '#4CAF50',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  accountServer: {
    fontSize: 14,
    color: '#4A6B8A',
    marginBottom: 4,
    fontWeight: '500',
  },
  lastUsed: {
    fontSize: 12,
    color: '#6B8CAE',
    fontStyle: 'italic',
  },
  quickLoginButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B8D4F1',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  quickLoginIcon: {
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: 'bold',
  },
  accountContentInner: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  removeButtonContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  removeButton: {
    width: 84,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#FF5C5C',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF5C5C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
    transform: [{ scale: 1 }],
  },
  removeButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  newAccountButton: {
    marginTop: 20,
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#4A90E2',
    borderStyle: 'dashed',
    alignItems: 'center',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  newAccountButtonText: {
    color: '#4A90E2',
    fontSize: 16,
    fontWeight: '500',
  },
  newAccountSection: {
    marginTop: 0,
  },
  newAccountModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 24,
    color: '#4A90E2',
    fontWeight: 'bold',
  },
  newAccountForm: {
    gap: 20,
  },
});

// Layout/behaviour constants
export const MAX_VISIBLE_ACCOUNTS = 1;
export const SWIPE_THRESHOLD = 80;
export const MAX_REVEAL = 100;
