import { Platform, StyleSheet } from 'react-native';

// FilesScreen styles extracted verbatim.

export const filesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8FF',
    paddingTop: 0,
  },
  headerContainer: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#B8D4F1',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  safeAreaSpacer: {
    height: Platform.OS === 'ios' ? 50 : 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 60,
    position: 'relative',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
  },
  backIcon: {
    fontSize: 20,
    color: '#4A90E2',
    fontWeight: '600',
    marginRight: 4,
  },
  backText: {
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: '500',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
  },
  headerActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B8D4F1',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  headerActionIcon: {
    fontSize: 16,
  },
  titleContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 80,
  },
  title: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1E3A5F',
    textAlign: 'center',
  },
  searchBarContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E6F2FF',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchInput: {
    height: 40,
    backgroundColor: '#F0F8FF',
    borderRadius: 20,
    paddingHorizontal: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#B8D4F1',
    color: '#1E3A5F',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: Platform.OS === 'ios' ? 110 : 110,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  fabDisabled: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
    shadowOpacity: 0.05,
    elevation: 1,
  },
  fabIcon: {
    fontSize: 24,
    color: '#4A90E2',
    fontWeight: '300',
    lineHeight: 24,
    textAlign: 'center',
  },
  content: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    fontSize: 16,
    color: '#4A6B8A',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: 16,
    opacity: 0.6,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1E3A5F',
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#4A6B8A',
    textAlign: 'center',
    lineHeight: 22,
  },
  listContainer: {
    padding: 16,
    gap: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FBFF',
    paddingHorizontal: 0,
    paddingVertical: 8,
    marginTop: 0,
    marginBottom: 2,
    marginHorizontal: -16,
    borderRadius: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E6F2FF',
    minHeight: 32,
  },
  sectionHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
    paddingLeft: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4A6B8A',
  },
  sectionCount: {
    fontSize: 12,
    color: '#7BA8D1',
    fontWeight: '400',
  },
  sectionCollapseIcon: {
    fontSize: 12,
    color: '#7BA8D1',
    fontWeight: '400',
    paddingRight: 16,
    paddingLeft: 8,
    textAlign: 'center',
    lineHeight: 16,
    minWidth: 16,
    alignSelf: 'center',
    transform: [{ rotate: '0deg' }],
  },
  sectionCollapseIconCollapsed: {
    transform: [{ rotate: '-90deg' }],
  },
  fileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    marginBottom: 1,
    borderWidth: 1,
    borderColor: '#E6F2FF',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  fileIcon: {
    width: 40,
    height: 40,
    backgroundColor: '#F0F8FF',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#D6E9F7',
  },
  fileIconText: {
    fontSize: 20,
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1E3A5F',
    marginBottom: 2,
  },
  fileDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  fileDetail: {
    fontSize: 12,
    color: '#4A6B8A',
  },
  chevron: {
    fontSize: 20,
    color: '#7BA8D1',
    fontWeight: '300',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(128, 128, 128, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#B8D4F1',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1E3A5F',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalInput: {
    height: 44,
    backgroundColor: '#F0F8FF',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#B8D4F1',
    color: '#1E3A5F',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#F0F8FF',
    borderWidth: 1,
    borderColor: '#B8D4F1',
  },
  modalButtonConfirm: {
    backgroundColor: '#4A90E2',
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A5F',
  },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E6F2FF',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 8,
  },
  bottomBarButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B8D4F1',
  },
  bottomBarButtonDisabled: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
  },
  bottomBarIcon: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4A90E2',
  },
  bottomBarIconDisabled: {
    color: '#C0C0C0',
  },
  bottomBarCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  bottomBarFolderName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1E3A5F',
    textAlign: 'center',
  },
  bottomBarDropdownIcon: {
    fontSize: 12,
    color: '#7BA8D1',
    marginLeft: 8,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
    paddingBottom: Platform.OS === 'ios' ? 80 : 22,
  },
  fabMenuOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingRight: 24,
    paddingBottom: Platform.OS === 'ios' ? 175 : 175,
  },
  bottomMenuModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 8,
    marginBottom: 0,
    width: 200,
    shadowColor: '#1E3A5F',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 20,
    borderWidth: 1,
    borderColor: '#E6F2FF',
  },
  centerMenuModal: {
    alignSelf: 'center',
    width: '65%',
    minWidth: 220,
  },
  rightMenuModal: {
    alignSelf: 'flex-end',
    marginRight: 8,
    width: 200,
  },
  fabMenuModal: {
    width: 220,
    marginBottom: 0,
    marginRight: 0,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A5F',
    textAlign: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E6F2FF',
    marginBottom: 4,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 2,
    minHeight: 44,
  },
  menuItemActive: {
    backgroundColor: '#F0F8FF',
    borderWidth: 1,
    borderColor: '#B8D4F1',
  },
  menuItemIcon: {
    fontSize: 18,
    marginRight: 12,
    width: 20,
    textAlign: 'center',
  },
  menuItemText: {
    fontSize: 16,
    color: '#1E3A5F',
    flex: 1,
    fontWeight: '500',
  },
  sortOrderIcon: {
    fontSize: 14,
    color: '#4A90E2',
    fontWeight: '600',
  },
  menuSeparator: {
    height: 1,
    backgroundColor: '#E6F2FF',
    marginVertical: 6,
    marginHorizontal: 8,
  },
  menuSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7BA8D1',
    textAlign: 'center',
    paddingVertical: 6,
    paddingHorizontal: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  userInfoSection: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: '#F8FBFF',
    marginHorizontal: 6,
    borderRadius: 6,
    marginTop: 4,
  },
  userInfoText: {
    fontSize: 12,
    color: '#7BA8D1',
    textAlign: 'center',
    marginBottom: 4,
  },
  userInfoUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A5F',
    textAlign: 'center',
  },
  userInfoShare: {
    fontSize: 14,
    color: '#4A6B8A',
    textAlign: 'center',
    marginTop: 2,
  },
});
