import { StyleSheet } from 'react-native';

// AclViewModal styles extracted verbatim.

export const aclStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8FF',
  },
  header: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#B0E0E6',
    backgroundColor: '#E6F3FF',
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#191970',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#4682B4',
    fontWeight: '400',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#4682B4',
  },
  noDataContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  noDataText: {
    fontSize: 16,
    color: '#4682B4',
    textAlign: 'center',
  },
  ownerContainer: {
    marginVertical: 8,
    padding: 16,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#87CEEB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  groupContainer: {
    marginVertical: 8,
    padding: 16,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#87CEEB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#191970',
  },
  expandIcon: {
    fontSize: 16,
    color: '#4169E1',
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  detailsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0F6FF',
  },
  defaultInfo: {
    marginBottom: 4,
  },
  ownerText: {
    fontSize: 15,
    color: '#191970',
    fontWeight: '500',
    marginBottom: 2,
  },
  ownerSubText: {
    fontSize: 13,
    color: '#5F9EA0',
    marginTop: 2,
  },
  groupText: {
    fontSize: 15,
    color: '#191970',
    fontWeight: '500',
    marginBottom: 2,
  },
  groupSubText: {
    fontSize: 13,
    color: '#5F9EA0',
    marginTop: 2,
  },
  acesContainer: {
    marginVertical: 8,
  },
  aceContainer: {
    marginVertical: 8,
    padding: 18,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1F5FE',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  aceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  identityContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  aceDefaultInfo: {
    flex: 1,
    marginRight: 12,
  },
  aceHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    flexWrap: 'wrap',
  },
  badgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aceSid: {
    fontSize: 14,
    color: '#191970',
    fontWeight: '500',
    flex: 1,
    marginLeft: 8,
  },
  permissionBadge: {
    fontSize: 11,
    color: '#FFFFFF',
    backgroundColor: '#4169E1',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginLeft: 8,
    marginRight: 12,
    shadowColor: '#4169E1',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  ownerBadge: {
    fontSize: 11,
    color: '#FFFFFF',
    backgroundColor: '#20C997',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginRight: 4,
    shadowColor: '#20C997',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  groupBadge: {
    fontSize: 11,
    color: '#FFFFFF',
    backgroundColor: '#6C63FF',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginRight: 4,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  aceDetails: {
    paddingTop: 12,
    paddingLeft: 0,
    borderTopWidth: 1,
    borderTopColor: '#E0F6FF',
    marginTop: 12,
  },
  aceSubText: {
    fontSize: 12,
    color: '#5F9EA0',
    marginTop: 3,
  },
  permissionsContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#F8FCFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E1F5FE',
    shadowColor: '#4169E1',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  permissionsTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#191970',
    marginBottom: 8,
  },
  permissionItem: {
    fontSize: 13,
    color: '#4682B4',
    marginVertical: 2,
    paddingLeft: 4,
  },
  closeButton: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#B0E0E6',
    backgroundColor: '#E6F3FF',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4169E1',
  },
  detailButton: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#E6F3FF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B0E0E6',
    alignSelf: 'flex-start',
  },
  detailButtonText: {
    fontSize: 12,
    color: '#4169E1',
    fontWeight: '500',
  },
  expandPermissionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#F0F8FF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B0E0E6',
  },
  expandPermissionText: {
    fontSize: 11,
    color: '#4169E1',
    fontWeight: '500',
  },
  expandPermissionIcon: {
    fontSize: 10,
    color: '#4169E1',
    marginLeft: 4,
  },
  detailedPermissionsContainer: {
    marginTop: 8,
    padding: 10,
    backgroundColor: '#F8FCFF',
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#87CEEB',
  },
  detailedPermissionsTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#191970',
    marginBottom: 6,
  },
  detailedPermissionItem: {
    fontSize: 11,
    color: '#5F9EA0',
    marginVertical: 1,
    paddingLeft: 4,
  },
  detailModalContainer: {
    flex: 1,
    backgroundColor: '#F0F8FF',
  },
  detailModalHeader: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#B0E0E6',
    backgroundColor: '#E6F3FF',
  },
  detailModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#191970',
    marginBottom: 4,
  },
  detailModalSubtitle: {
    fontSize: 14,
    color: '#4682B4',
    fontWeight: '400',
  },
  detailModalContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  allPermissionsContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#B0E0E6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  allPermissionsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#191970',
    marginBottom: 12,
  },
  permissionDetailItem: {
    marginVertical: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8FCFF',
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#87CEEB',
  },
  permissionDetailName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#191970',
    marginBottom: 4,
  },
  permissionDetailDescription: {
    fontSize: 12,
    color: '#5F9EA0',
    lineHeight: 16,
    paddingLeft: 8,
  },
  noPermissionsText: {
    fontSize: 16,
    color: '#4682B4',
    textAlign: 'center',
    marginTop: 40,
  },
  detailModalCloseButton: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#B0E0E6',
    backgroundColor: '#E6F3FF',
  },
  detailModalCloseButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4169E1',
  },
});
